version: '3.9'
services:

  webapp:
    restart: always
    container_name: webapp
    build: 
      context: ./
    volumes:
      - ./volumes/webapp:/app/vol
      #- .vol:/vol
    ports:
      - 8000:8000
    environment:
      - CONNECTION_STRING_MONGO=mongodb://test:test@mongodb:27017/?authMechanism=DEFAULT
    command: 
      ["python", "manage.py", "runserver", "0.0.0.0:8000"]


# CELERY

  redis:
    image: redis
    container_name: celery-redis
    restart: always
    ports:  
        - 6379:6379

  # flower:  
  #   image: mher/flower
  #   container_name: celery-flower
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - FLOWER_PORT=8888
  #   ports:  
  #     - 8889:8888

  worker:
    restart: always
    container_name: celery-worker
    environment:
      - CURRENT_ENVIROMENT=docker
      - CONNECTION_STRING_MONGO=mongodb://test:test@mongodb:27017/?authMechanism=DEFAULT
    build: 
      context: ./
    command: 
      ["celery", "--workdir=./", "-A", "test_task", "worker"]
    
# MongoDB

  database:
    image: mongo
    container_name: mongodb
    environment:
      # - MONGO_INITDB_DATABASE=testdb
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - 27017:27017
    volumes:
      # - ./volumes/mongo:/data/db
      - ./volumes/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


# NETWORK

networks:
  default:
    name: testtask-network